# Generated by Django 4.2.6 on 2023-10-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_creation', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'permissions': [('start_and_stop_newsletter', 'Can start and stop newsletter')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('completed', 'Завершена'), ('created', 'Создана'), ('running', 'Запущена'), ('paused', 'Приостановлена')], default='created', max_length=40),
        ),
    ]
